/*
 * boneMapping.ts - Maps GLB model node names to application bone IDs and regions
 * The GLB model from AnatomyTOOL has right-side bones (.r suffix) that need mirroring
 * 
 * Structure:
 *   "Bones" group (node 36) → midline/axial bones (no .r suffix)
 *   "Bones_right" group (node 135) → right-side bones (.r suffix)
 *   "Cartilages_right" group (node 146) → costal cartilages (.r suffix)
 *   Left-side bones are generated by mirroring right-side bones (scale X by -1)
 */

export type RegionId =
  | 'skull'
  | 'spine'
  | 'thorax'
  | 'upper-limb-left'
  | 'upper-limb-right'
  | 'pelvis'
  | 'lower-limb-left'
  | 'lower-limb-right';

export interface BoneMappingEntry {
  /** Application-level bone ID used in BONE_INFO, pathology, etc. */
  appBoneId: string;
  /** Display name in Chinese */
  nameCn: string;
  /** Display name in English */
  nameEn: string;
  /** Region this bone belongs to */
  region: RegionId;
  /** Whether this bone should be mirrored to create a left-side counterpart */
  mirror: boolean;
  /** The mirrored bone's appBoneId (if mirror=true) */
  mirrorAppBoneId?: string;
}

/**
 * Maps GLB node names → application bone metadata.
 * Key = exact node.name from the GLB file.
 * 
 * Midline bones (in "Bones" group) have no .r suffix and mirror=false.
 * Right-side bones (in "Bones_right" group) have .r suffix and mirror=true.
 */
export const GLB_NODE_TO_BONE: Record<string, BoneMappingEntry> = {
  // ==================== AXIAL SKELETON (Bones group) ====================
  // -- Skull --
  'Frontal bone': { appBoneId: 'frontal-bone', nameCn: '额骨', nameEn: 'Frontal Bone', region: 'skull', mirror: false },
  'Parietal bone left': { appBoneId: 'parietal-bone-left', nameCn: '顶骨（左）', nameEn: 'Parietal Bone (Left)', region: 'skull', mirror: false },
  'Parietal bone right': { appBoneId: 'parietal-bone-right', nameCn: '顶骨（右）', nameEn: 'Parietal Bone (Right)', region: 'skull', mirror: false },
  'Occipital bone': { appBoneId: 'occipital-bone', nameCn: '枕骨', nameEn: 'Occipital Bone', region: 'skull', mirror: false },
  'Sphenoid bone': { appBoneId: 'sphenoid-bone', nameCn: '蝶骨', nameEn: 'Sphenoid Bone', region: 'skull', mirror: false },
  'Ethmoid Bone': { appBoneId: 'ethmoid-bone', nameCn: '筛骨', nameEn: 'Ethmoid Bone', region: 'skull', mirror: false },
  'Vomer': { appBoneId: 'vomer', nameCn: '犁骨', nameEn: 'Vomer', region: 'skull', mirror: false },
  'Mandible bone': { appBoneId: 'mandible', nameCn: '下颌骨', nameEn: 'Mandible', region: 'skull', mirror: false },

  // -- Spine: Cervical --
  'Atlas (C1)': { appBoneId: 'atlas-c1', nameCn: '寰椎 (C1)', nameEn: 'Atlas (C1)', region: 'spine', mirror: false },
  'Axis (C2)': { appBoneId: 'axis-c2', nameCn: '枢椎 (C2)', nameEn: 'Axis (C2)', region: 'spine', mirror: false },
  'Cervical vertebrae (C3)': { appBoneId: 'cervical-c3', nameCn: '颈椎 (C3)', nameEn: 'Cervical Vertebra (C3)', region: 'spine', mirror: false },
  'Cervical vertebrae (C4)': { appBoneId: 'cervical-c4', nameCn: '颈椎 (C4)', nameEn: 'Cervical Vertebra (C4)', region: 'spine', mirror: false },
  'Cervical vertebrae (C5)': { appBoneId: 'cervical-c5', nameCn: '颈椎 (C5)', nameEn: 'Cervical Vertebra (C5)', region: 'spine', mirror: false },
  'Cervical vertebrae (C6)': { appBoneId: 'cervical-c6', nameCn: '颈椎 (C6)', nameEn: 'Cervical Vertebra (C6)', region: 'spine', mirror: false },
  'Cervical vertebrae (C7)': { appBoneId: 'cervical-c7', nameCn: '颈椎 (C7)', nameEn: 'Cervical Vertebra (C7)', region: 'spine', mirror: false },

  // -- Spine: Thoracic --
  'Thoracic vertebrae (T1)': { appBoneId: 'thoracic-t1', nameCn: '胸椎 (T1)', nameEn: 'Thoracic Vertebra (T1)', region: 'spine', mirror: false },
  'Thoracic vertebrae (T2)': { appBoneId: 'thoracic-t2', nameCn: '胸椎 (T2)', nameEn: 'Thoracic Vertebra (T2)', region: 'spine', mirror: false },
  'Thoracic vertebrae (T3)': { appBoneId: 'thoracic-t3', nameCn: '胸椎 (T3)', nameEn: 'Thoracic Vertebra (T3)', region: 'spine', mirror: false },
  'Thoracic vertebrae (T4)': { appBoneId: 'thoracic-t4', nameCn: '胸椎 (T4)', nameEn: 'Thoracic Vertebra (T4)', region: 'spine', mirror: false },
  'Thoracic vertebrae (T5)': { appBoneId: 'thoracic-t5', nameCn: '胸椎 (T5)', nameEn: 'Thoracic Vertebra (T5)', region: 'spine', mirror: false },
  'Thoracic vertebrae (T6)': { appBoneId: 'thoracic-t6', nameCn: '胸椎 (T6)', nameEn: 'Thoracic Vertebra (T6)', region: 'spine', mirror: false },
  'Thoracic vertebrae (T7)': { appBoneId: 'thoracic-t7', nameCn: '胸椎 (T7)', nameEn: 'Thoracic Vertebra (T7)', region: 'spine', mirror: false },
  'Thoracic vertebrae (T8)': { appBoneId: 'thoracic-t8', nameCn: '胸椎 (T8)', nameEn: 'Thoracic Vertebra (T8)', region: 'spine', mirror: false },
  'Thoracic vertebrae (T9)': { appBoneId: 'thoracic-t9', nameCn: '胸椎 (T9)', nameEn: 'Thoracic Vertebra (T9)', region: 'spine', mirror: false },
  'Thoracic vertebrae (T10)': { appBoneId: 'thoracic-t10', nameCn: '胸椎 (T10)', nameEn: 'Thoracic Vertebra (T10)', region: 'spine', mirror: false },
  'Thoracic vertebrae (T11)': { appBoneId: 'thoracic-t11', nameCn: '胸椎 (T11)', nameEn: 'Thoracic Vertebra (T11)', region: 'spine', mirror: false },
  'Thoracic vertebrae (T12)': { appBoneId: 'thoracic-t12', nameCn: '胸椎 (T12)', nameEn: 'Thoracic Vertebra (T12)', region: 'spine', mirror: false },

  // -- Spine: Lumbar --
  'Lumbar vertebrae (L1)': { appBoneId: 'lumbar-l1', nameCn: '腰椎 (L1)', nameEn: 'Lumbar Vertebra (L1)', region: 'spine', mirror: false },
  'Lumbar vertebrae (L2)': { appBoneId: 'lumbar-l2', nameCn: '腰椎 (L2)', nameEn: 'Lumbar Vertebra (L2)', region: 'spine', mirror: false },
  'Lumbar vertebrae (L3)': { appBoneId: 'lumbar-l3', nameCn: '腰椎 (L3)', nameEn: 'Lumbar Vertebra (L3)', region: 'spine', mirror: false },
  'Lumbar vertebrae (L4)': { appBoneId: 'lumbar-l4', nameCn: '腰椎 (L4)', nameEn: 'Lumbar Vertebra (L4)', region: 'spine', mirror: false },
  'Lumbar vertebrae (L5)': { appBoneId: 'lumbar-l5', nameCn: '腰椎 (L5)', nameEn: 'Lumbar Vertebra (L5)', region: 'spine', mirror: false },

  // -- Spine: Sacrum & Coccyx --
  'Sacrum': { appBoneId: 'sacrum', nameCn: '骶骨', nameEn: 'Sacrum', region: 'spine', mirror: false },
  'Coccyx': { appBoneId: 'coccyx', nameCn: '尾骨', nameEn: 'Coccyx', region: 'spine', mirror: false },

  // -- Thorax: Sternum --
  'Body of sternum': { appBoneId: 'sternum-body', nameCn: '胸骨体', nameEn: 'Body of Sternum', region: 'thorax', mirror: false },
  'Manubrium of sternum': { appBoneId: 'sternum-manubrium', nameCn: '胸骨柄', nameEn: 'Manubrium of Sternum', region: 'thorax', mirror: false },

  // ==================== RIGHT-SIDE BONES (Bones_right group) ====================
  // -- Skull (right-side paired) --
  'Temporal bone.r': { appBoneId: 'temporal-bone-right', nameCn: '颞骨（右）', nameEn: 'Temporal Bone (R)', region: 'skull', mirror: true, mirrorAppBoneId: 'temporal-bone-left' },
  'Zygomatic bone.r': { appBoneId: 'zygomatic-bone-right', nameCn: '颧骨（右）', nameEn: 'Zygomatic Bone (R)', region: 'skull', mirror: true, mirrorAppBoneId: 'zygomatic-bone-left' },
  'Maxilla bone.r': { appBoneId: 'maxilla-right', nameCn: '上颌骨（右）', nameEn: 'Maxilla (R)', region: 'skull', mirror: true, mirrorAppBoneId: 'maxilla-left' },
  'Nasal bone.r': { appBoneId: 'nasal-bone-right', nameCn: '鼻骨（右）', nameEn: 'Nasal Bone (R)', region: 'skull', mirror: true, mirrorAppBoneId: 'nasal-bone-left' },
  'Lacrimal bone.r': { appBoneId: 'lacrimal-bone-right', nameCn: '泪骨（右）', nameEn: 'Lacrimal Bone (R)', region: 'skull', mirror: true, mirrorAppBoneId: 'lacrimal-bone-left' },
  'Inferior nasal concha bone.r': { appBoneId: 'inferior-nasal-concha-right', nameCn: '下鼻甲（右）', nameEn: 'Inferior Nasal Concha (R)', region: 'skull', mirror: true, mirrorAppBoneId: 'inferior-nasal-concha-left' },
  'Palatine bone.r': { appBoneId: 'palatine-bone-right', nameCn: '腭骨（右）', nameEn: 'Palatine Bone (R)', region: 'skull', mirror: true, mirrorAppBoneId: 'palatine-bone-left' },

  // -- Upper Limb --
  'Clavicle.r': { appBoneId: 'clavicle-right', nameCn: '锁骨（右）', nameEn: 'Clavicle (R)', region: 'upper-limb-right', mirror: true, mirrorAppBoneId: 'clavicle-left' },
  'Scapula.r.': { appBoneId: 'scapula-right', nameCn: '肩胛骨（右）', nameEn: 'Scapula (R)', region: 'upper-limb-right', mirror: true, mirrorAppBoneId: 'scapula-left' },
  'Humerus.r': { appBoneId: 'humerus-right', nameCn: '肱骨（右）', nameEn: 'Humerus (R)', region: 'upper-limb-right', mirror: true, mirrorAppBoneId: 'humerus-left' },
  'Radius.r': { appBoneId: 'radius-right', nameCn: '桡骨（右）', nameEn: 'Radius (R)', region: 'upper-limb-right', mirror: true, mirrorAppBoneId: 'radius-left' },
  'Ulna.r': { appBoneId: 'ulna-right', nameCn: '尺骨（右）', nameEn: 'Ulna (R)', region: 'upper-limb-right', mirror: true, mirrorAppBoneId: 'ulna-left' },

  // -- Hand bones --
  '1st metacarpal bone.r': { appBoneId: 'metacarpal-1-right', nameCn: '第1掌骨（右）', nameEn: '1st Metacarpal (R)', region: 'upper-limb-right', mirror: true, mirrorAppBoneId: 'metacarpal-1-left' },
  '2nd metacarpal bone.r': { appBoneId: 'metacarpal-2-right', nameCn: '第2掌骨（右）', nameEn: '2nd Metacarpal (R)', region: 'upper-limb-right', mirror: true, mirrorAppBoneId: 'metacarpal-2-left' },
  '3rd metacarpal bone.r': { appBoneId: 'metacarpal-3-right', nameCn: '第3掌骨（右）', nameEn: '3rd Metacarpal (R)', region: 'upper-limb-right', mirror: true, mirrorAppBoneId: 'metacarpal-3-left' },
  '4th metacarpal bone.r': { appBoneId: 'metacarpal-4-right', nameCn: '第4掌骨（右）', nameEn: '4th Metacarpal (R)', region: 'upper-limb-right', mirror: true, mirrorAppBoneId: 'metacarpal-4-left' },
  '5th metacarpal bone.r': { appBoneId: 'metacarpal-5-right', nameCn: '第5掌骨（右）', nameEn: '5th Metacarpal (R)', region: 'upper-limb-right', mirror: true, mirrorAppBoneId: 'metacarpal-5-left' },

  // Carpal bones
  'Scaphoid.r': { appBoneId: 'scaphoid-right', nameCn: '舟骨（右）', nameEn: 'Scaphoid (R)', region: 'upper-limb-right', mirror: true, mirrorAppBoneId: 'scaphoid-left' },
  'Lunate bone.r': { appBoneId: 'lunate-right', nameCn: '月骨（右）', nameEn: 'Lunate (R)', region: 'upper-limb-right', mirror: true, mirrorAppBoneId: 'lunate-left' },
  'Triquetrum.r': { appBoneId: 'triquetrum-right', nameCn: '三角骨（右）', nameEn: 'Triquetrum (R)', region: 'upper-limb-right', mirror: true, mirrorAppBoneId: 'triquetrum-left' },
  'Pisiform.r': { appBoneId: 'pisiform-right', nameCn: '豌豆骨（右）', nameEn: 'Pisiform (R)', region: 'upper-limb-right', mirror: true, mirrorAppBoneId: 'pisiform-left' },
  'Trapezium.r': { appBoneId: 'trapezium-right', nameCn: '大多角骨（右）', nameEn: 'Trapezium (R)', region: 'upper-limb-right', mirror: true, mirrorAppBoneId: 'trapezium-left' },
  'Trapezoid.r': { appBoneId: 'trapezoid-right', nameCn: '小多角骨（右）', nameEn: 'Trapezoid (R)', region: 'upper-limb-right', mirror: true, mirrorAppBoneId: 'trapezoid-left' },
  'Capitate.r': { appBoneId: 'capitate-right', nameCn: '头状骨（右）', nameEn: 'Capitate (R)', region: 'upper-limb-right', mirror: true, mirrorAppBoneId: 'capitate-left' },
  'Hamate.r': { appBoneId: 'hamate-right', nameCn: '钩骨（右）', nameEn: 'Hamate (R)', region: 'upper-limb-right', mirror: true, mirrorAppBoneId: 'hamate-left' },
  'Sesamoid_bones_of_hand.r': { appBoneId: 'sesamoid-hand-right', nameCn: '手籽骨（右）', nameEn: 'Sesamoid Bones of Hand (R)', region: 'upper-limb-right', mirror: true, mirrorAppBoneId: 'sesamoid-hand-left' },

  // Finger phalanges
  'Proximal phalanx of 1st finger.r': { appBoneId: 'prox-phalanx-f1-right', nameCn: '拇指近节指骨（右）', nameEn: 'Proximal Phalanx of Thumb (R)', region: 'upper-limb-right', mirror: true, mirrorAppBoneId: 'prox-phalanx-f1-left' },
  'Proximal phalanx of 2d finger.r': { appBoneId: 'prox-phalanx-f2-right', nameCn: '食指近节指骨（右）', nameEn: 'Proximal Phalanx of Index (R)', region: 'upper-limb-right', mirror: true, mirrorAppBoneId: 'prox-phalanx-f2-left' },
  'Proximal phalanx of 3rd finger.r': { appBoneId: 'prox-phalanx-f3-right', nameCn: '中指近节指骨（右）', nameEn: 'Proximal Phalanx of Middle (R)', region: 'upper-limb-right', mirror: true, mirrorAppBoneId: 'prox-phalanx-f3-left' },
  'Proximal phalanx of 4th finger.r': { appBoneId: 'prox-phalanx-f4-right', nameCn: '无名指近节指骨（右）', nameEn: 'Proximal Phalanx of Ring (R)', region: 'upper-limb-right', mirror: true, mirrorAppBoneId: 'prox-phalanx-f4-left' },
  'Proximal phalanx of 5th finger.r': { appBoneId: 'prox-phalanx-f5-right', nameCn: '小指近节指骨（右）', nameEn: 'Proximal Phalanx of Little (R)', region: 'upper-limb-right', mirror: true, mirrorAppBoneId: 'prox-phalanx-f5-left' },
  'Middle phalanx of 2d finger.r': { appBoneId: 'mid-phalanx-f2-right', nameCn: '食指中节指骨（右）', nameEn: 'Middle Phalanx of Index (R)', region: 'upper-limb-right', mirror: true, mirrorAppBoneId: 'mid-phalanx-f2-left' },
  'Middle phalanx of 3rd finger.r': { appBoneId: 'mid-phalanx-f3-right', nameCn: '中指中节指骨（右）', nameEn: 'Middle Phalanx of Middle (R)', region: 'upper-limb-right', mirror: true, mirrorAppBoneId: 'mid-phalanx-f3-left' },
  'Middle phalanx of 4th finger.r': { appBoneId: 'mid-phalanx-f4-right', nameCn: '无名指中节指骨（右）', nameEn: 'Middle Phalanx of Ring (R)', region: 'upper-limb-right', mirror: true, mirrorAppBoneId: 'mid-phalanx-f4-left' },
  'Middle phalanx of 5th finger.r': { appBoneId: 'mid-phalanx-f5-right', nameCn: '小指中节指骨（右）', nameEn: 'Middle Phalanx of Little (R)', region: 'upper-limb-right', mirror: true, mirrorAppBoneId: 'mid-phalanx-f5-left' },
  'Distal phalanx of 1st finger.r': { appBoneId: 'dist-phalanx-f1-right', nameCn: '拇指远节指骨（右）', nameEn: 'Distal Phalanx of Thumb (R)', region: 'upper-limb-right', mirror: true, mirrorAppBoneId: 'dist-phalanx-f1-left' },
  'Distal phalanx of 2d finger.r': { appBoneId: 'dist-phalanx-f2-right', nameCn: '食指远节指骨（右）', nameEn: 'Distal Phalanx of Index (R)', region: 'upper-limb-right', mirror: true, mirrorAppBoneId: 'dist-phalanx-f2-left' },
  'Distal phalanx of 3d finger.r': { appBoneId: 'dist-phalanx-f3-right', nameCn: '中指远节指骨（右）', nameEn: 'Distal Phalanx of Middle (R)', region: 'upper-limb-right', mirror: true, mirrorAppBoneId: 'dist-phalanx-f3-left' },
  'Distal phalanx of 4th finger.r': { appBoneId: 'dist-phalanx-f4-right', nameCn: '无名指远节指骨（右）', nameEn: 'Distal Phalanx of Ring (R)', region: 'upper-limb-right', mirror: true, mirrorAppBoneId: 'dist-phalanx-f4-left' },
  'Distal phalanx of 5th finger.r': { appBoneId: 'dist-phalanx-f5-right', nameCn: '小指远节指骨（右）', nameEn: 'Distal Phalanx of Little (R)', region: 'upper-limb-right', mirror: true, mirrorAppBoneId: 'dist-phalanx-f5-left' },

  // -- Pelvis --
  'Hip bone.r': { appBoneId: 'hip-bone-right', nameCn: '髋骨（右）', nameEn: 'Hip Bone (R)', region: 'pelvis', mirror: true, mirrorAppBoneId: 'hip-bone-left' },

  // -- Lower Limb --
  'Femur.r': { appBoneId: 'femur-right', nameCn: '股骨（右）', nameEn: 'Femur (R)', region: 'lower-limb-right', mirror: true, mirrorAppBoneId: 'femur-left' },
  'Patella.r': { appBoneId: 'patella-right', nameCn: '髌骨（右）', nameEn: 'Patella (R)', region: 'lower-limb-right', mirror: true, mirrorAppBoneId: 'patella-left' },
  'Tibia.r': { appBoneId: 'tibia-right', nameCn: '胫骨（右）', nameEn: 'Tibia (R)', region: 'lower-limb-right', mirror: true, mirrorAppBoneId: 'tibia-left' },
  'Fibula.r': { appBoneId: 'fibula-right', nameCn: '腓骨（右）', nameEn: 'Fibula (R)', region: 'lower-limb-right', mirror: true, mirrorAppBoneId: 'fibula-left' },

  // Tarsal bones
  'Calcaneus.r': { appBoneId: 'calcaneus-right', nameCn: '跟骨（右）', nameEn: 'Calcaneus (R)', region: 'lower-limb-right', mirror: true, mirrorAppBoneId: 'calcaneus-left' },
  'Talus.r': { appBoneId: 'talus-right', nameCn: '距骨（右）', nameEn: 'Talus (R)', region: 'lower-limb-right', mirror: true, mirrorAppBoneId: 'talus-left' },
  'Navicular bone.r': { appBoneId: 'navicular-right', nameCn: '足舟骨（右）', nameEn: 'Navicular (R)', region: 'lower-limb-right', mirror: true, mirrorAppBoneId: 'navicular-left' },
  'Cuboid bone.r': { appBoneId: 'cuboid-right', nameCn: '骰骨（右）', nameEn: 'Cuboid (R)', region: 'lower-limb-right', mirror: true, mirrorAppBoneId: 'cuboid-left' },
  'Medial cuneiform bone.r': { appBoneId: 'medial-cuneiform-right', nameCn: '内侧楔骨（右）', nameEn: 'Medial Cuneiform (R)', region: 'lower-limb-right', mirror: true, mirrorAppBoneId: 'medial-cuneiform-left' },
  'Intermediate cuneiform bone.r': { appBoneId: 'intermediate-cuneiform-right', nameCn: '中间楔骨（右）', nameEn: 'Intermediate Cuneiform (R)', region: 'lower-limb-right', mirror: true, mirrorAppBoneId: 'intermediate-cuneiform-left' },
  'Lateral cuneiform bone.r': { appBoneId: 'lateral-cuneiform-right', nameCn: '外侧楔骨（右）', nameEn: 'Lateral Cuneiform (R)', region: 'lower-limb-right', mirror: true, mirrorAppBoneId: 'lateral-cuneiform-left' },

  // Metatarsals
  'First metatarsal bone.r': { appBoneId: 'metatarsal-1-right', nameCn: '第1跖骨（右）', nameEn: '1st Metatarsal (R)', region: 'lower-limb-right', mirror: true, mirrorAppBoneId: 'metatarsal-1-left' },
  'Second metatarsal bone.r': { appBoneId: 'metatarsal-2-right', nameCn: '第2跖骨（右）', nameEn: '2nd Metatarsal (R)', region: 'lower-limb-right', mirror: true, mirrorAppBoneId: 'metatarsal-2-left' },
  'Third metatarsal bone.r': { appBoneId: 'metatarsal-3-right', nameCn: '第3跖骨（右）', nameEn: '3rd Metatarsal (R)', region: 'lower-limb-right', mirror: true, mirrorAppBoneId: 'metatarsal-3-left' },
  'Fourth metatarsal bone.r': { appBoneId: 'metatarsal-4-right', nameCn: '第4跖骨（右）', nameEn: '4th Metatarsal (R)', region: 'lower-limb-right', mirror: true, mirrorAppBoneId: 'metatarsal-4-left' },
  'Fifth metatarsal bone.r': { appBoneId: 'metatarsal-5-right', nameCn: '第5跖骨（右）', nameEn: '5th Metatarsal (R)', region: 'lower-limb-right', mirror: true, mirrorAppBoneId: 'metatarsal-5-left' },
  'Sesamoid bones of foot.r': { appBoneId: 'sesamoid-foot-right', nameCn: '足籽骨（右）', nameEn: 'Sesamoid Bones of Foot (R)', region: 'lower-limb-right', mirror: true, mirrorAppBoneId: 'sesamoid-foot-left' },

  // Toe phalanges
  'Proximal phalanx of first finger of foot.r': { appBoneId: 'prox-phalanx-t1-right', nameCn: '拇趾近节趾骨（右）', nameEn: 'Proximal Phalanx of Great Toe (R)', region: 'lower-limb-right', mirror: true, mirrorAppBoneId: 'prox-phalanx-t1-left' },
  'Proximal phalanx of second finger of foot.r': { appBoneId: 'prox-phalanx-t2-right', nameCn: '第2趾近节趾骨（右）', nameEn: 'Proximal Phalanx of 2nd Toe (R)', region: 'lower-limb-right', mirror: true, mirrorAppBoneId: 'prox-phalanx-t2-left' },
  'Proximal phalanx of third finger of foot.r': { appBoneId: 'prox-phalanx-t3-right', nameCn: '第3趾近节趾骨（右）', nameEn: 'Proximal Phalanx of 3rd Toe (R)', region: 'lower-limb-right', mirror: true, mirrorAppBoneId: 'prox-phalanx-t3-left' },
  'Proximal phalanx of fourth finger of foot.r': { appBoneId: 'prox-phalanx-t4-right', nameCn: '第4趾近节趾骨（右）', nameEn: 'Proximal Phalanx of 4th Toe (R)', region: 'lower-limb-right', mirror: true, mirrorAppBoneId: 'prox-phalanx-t4-left' },
  'Proximal phalanx of fifth finger of foot.r': { appBoneId: 'prox-phalanx-t5-right', nameCn: '第5趾近节趾骨（右）', nameEn: 'Proximal Phalanx of 5th Toe (R)', region: 'lower-limb-right', mirror: true, mirrorAppBoneId: 'prox-phalanx-t5-left' },
  'Middle phalanx of second finger of foot.r': { appBoneId: 'mid-phalanx-t2-right', nameCn: '第2趾中节趾骨（右）', nameEn: 'Middle Phalanx of 2nd Toe (R)', region: 'lower-limb-right', mirror: true, mirrorAppBoneId: 'mid-phalanx-t2-left' },
  'Middle phalanx of third finger of foot.r': { appBoneId: 'mid-phalanx-t3-right', nameCn: '第3趾中节趾骨（右）', nameEn: 'Middle Phalanx of 3rd Toe (R)', region: 'lower-limb-right', mirror: true, mirrorAppBoneId: 'mid-phalanx-t3-left' },
  'Middle phalanx of fourth finger of foot.r': { appBoneId: 'mid-phalanx-t4-right', nameCn: '第4趾中节趾骨（右）', nameEn: 'Middle Phalanx of 4th Toe (R)', region: 'lower-limb-right', mirror: true, mirrorAppBoneId: 'mid-phalanx-t4-left' },
  'Middle phalanx of fifth finger of foot.r': { appBoneId: 'mid-phalanx-t5-right', nameCn: '第5趾中节趾骨（右）', nameEn: 'Middle Phalanx of 5th Toe (R)', region: 'lower-limb-right', mirror: true, mirrorAppBoneId: 'mid-phalanx-t5-left' },
  'Distal phalanx of first finger of foot.r': { appBoneId: 'dist-phalanx-t1-right', nameCn: '拇趾远节趾骨（右）', nameEn: 'Distal Phalanx of Great Toe (R)', region: 'lower-limb-right', mirror: true, mirrorAppBoneId: 'dist-phalanx-t1-left' },
  'Distal phalanx of second finger of foot.r': { appBoneId: 'dist-phalanx-t2-right', nameCn: '第2趾远节趾骨（右）', nameEn: 'Distal Phalanx of 2nd Toe (R)', region: 'lower-limb-right', mirror: true, mirrorAppBoneId: 'dist-phalanx-t2-left' },
  'Distal phalanx of third finger of foot.r': { appBoneId: 'dist-phalanx-t3-right', nameCn: '第3趾远节趾骨（右）', nameEn: 'Distal Phalanx of 3rd Toe (R)', region: 'lower-limb-right', mirror: true, mirrorAppBoneId: 'dist-phalanx-t3-left' },
  'Distal phalanx of fourth finger of foot.r': { appBoneId: 'dist-phalanx-t4-right', nameCn: '第4趾远节趾骨（右）', nameEn: 'Distal Phalanx of 4th Toe (R)', region: 'lower-limb-right', mirror: true, mirrorAppBoneId: 'dist-phalanx-t4-left' },
  'Distal phalanx of fifth finger of foot.r': { appBoneId: 'dist-phalanx-t5-right', nameCn: '第5趾远节趾骨（右）', nameEn: 'Distal Phalanx of 5th Toe (R)', region: 'lower-limb-right', mirror: true, mirrorAppBoneId: 'dist-phalanx-t5-left' },

  // -- Ribs --
  'Rib (1st).r': { appBoneId: 'rib-1-right', nameCn: '第1肋（右）', nameEn: '1st Rib (R)', region: 'thorax', mirror: true, mirrorAppBoneId: 'rib-1-left' },
  'Rib (2nd).r': { appBoneId: 'rib-2-right', nameCn: '第2肋（右）', nameEn: '2nd Rib (R)', region: 'thorax', mirror: true, mirrorAppBoneId: 'rib-2-left' },
  'Rib (3rd).r': { appBoneId: 'rib-3-right', nameCn: '第3肋（右）', nameEn: '3rd Rib (R)', region: 'thorax', mirror: true, mirrorAppBoneId: 'rib-3-left' },
  'Rib (4th).r': { appBoneId: 'rib-4-right', nameCn: '第4肋（右）', nameEn: '4th Rib (R)', region: 'thorax', mirror: true, mirrorAppBoneId: 'rib-4-left' },
  'Rib (5th).r': { appBoneId: 'rib-5-right', nameCn: '第5肋（右）', nameEn: '5th Rib (R)', region: 'thorax', mirror: true, mirrorAppBoneId: 'rib-5-left' },
  'Rib (6th).r': { appBoneId: 'rib-6-right', nameCn: '第6肋（右）', nameEn: '6th Rib (R)', region: 'thorax', mirror: true, mirrorAppBoneId: 'rib-6-left' },
  'Rib (7th).r': { appBoneId: 'rib-7-right', nameCn: '第7肋（右）', nameEn: '7th Rib (R)', region: 'thorax', mirror: true, mirrorAppBoneId: 'rib-7-left' },
  'Rib (8th).r': { appBoneId: 'rib-8-right', nameCn: '第8肋（右）', nameEn: '8th Rib (R)', region: 'thorax', mirror: true, mirrorAppBoneId: 'rib-8-left' },
  'Rib (9th).r': { appBoneId: 'rib-9-right', nameCn: '第9肋（右）', nameEn: '9th Rib (R)', region: 'thorax', mirror: true, mirrorAppBoneId: 'rib-9-left' },
  'Rib (10th).r': { appBoneId: 'rib-10-right', nameCn: '第10肋（右）', nameEn: '10th Rib (R)', region: 'thorax', mirror: true, mirrorAppBoneId: 'rib-10-left' },
  'Rib (11th).r': { appBoneId: 'rib-11-right', nameCn: '第11肋（右）', nameEn: '11th Rib (R)', region: 'thorax', mirror: true, mirrorAppBoneId: 'rib-11-left' },
  'Rib (12th).r': { appBoneId: 'rib-12-right', nameCn: '第12肋（右）', nameEn: '12th Rib (R)', region: 'thorax', mirror: true, mirrorAppBoneId: 'rib-12-left' },

  // -- Teeth (upper) --
  'Upper medial incisor.r': { appBoneId: 'upper-medial-incisor-right', nameCn: '上中切牙（右）', nameEn: 'Upper Medial Incisor (R)', region: 'skull', mirror: true, mirrorAppBoneId: 'upper-medial-incisor-left' },
  'Upper lateral incisor.r': { appBoneId: 'upper-lateral-incisor-right', nameCn: '上侧切牙（右）', nameEn: 'Upper Lateral Incisor (R)', region: 'skull', mirror: true, mirrorAppBoneId: 'upper-lateral-incisor-left' },
  'Upper canine.r': { appBoneId: 'upper-canine-right', nameCn: '上尖牙（右）', nameEn: 'Upper Canine (R)', region: 'skull', mirror: true, mirrorAppBoneId: 'upper-canine-left' },
  'Upper first premolar.r': { appBoneId: 'upper-first-premolar-right', nameCn: '上第一前磨牙（右）', nameEn: 'Upper 1st Premolar (R)', region: 'skull', mirror: true, mirrorAppBoneId: 'upper-first-premolar-left' },
  'Upper second premolar.r': { appBoneId: 'upper-second-premolar-right', nameCn: '上第二前磨牙（右）', nameEn: 'Upper 2nd Premolar (R)', region: 'skull', mirror: true, mirrorAppBoneId: 'upper-second-premolar-left' },
  'Upper first molar tooth.r': { appBoneId: 'upper-first-molar-right', nameCn: '上第一磨牙（右）', nameEn: 'Upper 1st Molar (R)', region: 'skull', mirror: true, mirrorAppBoneId: 'upper-first-molar-left' },
  'Upper second molar tooth.r': { appBoneId: 'upper-second-molar-right', nameCn: '上第二磨牙（右）', nameEn: 'Upper 2nd Molar (R)', region: 'skull', mirror: true, mirrorAppBoneId: 'upper-second-molar-left' },

  // -- Teeth (lower) --
  'Lower medial incisor.r': { appBoneId: 'lower-medial-incisor-right', nameCn: '下中切牙（右）', nameEn: 'Lower Medial Incisor (R)', region: 'skull', mirror: true, mirrorAppBoneId: 'lower-medial-incisor-left' },
  'Lower lateral incisor.r': { appBoneId: 'lower-lateral-incisor-right', nameCn: '下侧切牙（右）', nameEn: 'Lower Lateral Incisor (R)', region: 'skull', mirror: true, mirrorAppBoneId: 'lower-lateral-incisor-left' },
  'Lower canine.r': { appBoneId: 'lower-canine-right', nameCn: '下尖牙（右）', nameEn: 'Lower Canine (R)', region: 'skull', mirror: true, mirrorAppBoneId: 'lower-canine-left' },
  'Lower first premolar.r': { appBoneId: 'lower-first-premolar-right', nameCn: '下第一前磨牙（右）', nameEn: 'Lower 1st Premolar (R)', region: 'skull', mirror: true, mirrorAppBoneId: 'lower-first-premolar-left' },
  'Lower second premolar.r': { appBoneId: 'lower-second-premolar-right', nameCn: '下第二前磨牙（右）', nameEn: 'Lower 2nd Premolar (R)', region: 'skull', mirror: true, mirrorAppBoneId: 'lower-second-premolar-left' },
  'Lower first molar tooth.r': { appBoneId: 'lower-first-molar-right', nameCn: '下第一磨牙（右）', nameEn: 'Lower 1st Molar (R)', region: 'skull', mirror: true, mirrorAppBoneId: 'lower-first-molar-left' },
  'Lower second molar tooth.r': { appBoneId: 'lower-second-molar-right', nameCn: '下第二磨牙（右）', nameEn: 'Lower 2nd Molar (R)', region: 'skull', mirror: true, mirrorAppBoneId: 'lower-second-molar-left' },

  // -- Costal Cartilages --
  'Costal cart of 1st rib.r': { appBoneId: 'costal-cart-1-right', nameCn: '第1肋软骨（右）', nameEn: '1st Costal Cartilage (R)', region: 'thorax', mirror: true, mirrorAppBoneId: 'costal-cart-1-left' },
  'Costal cart of 2nd rib.r': { appBoneId: 'costal-cart-2-right', nameCn: '第2肋软骨（右）', nameEn: '2nd Costal Cartilage (R)', region: 'thorax', mirror: true, mirrorAppBoneId: 'costal-cart-2-left' },
  'Costal cart of 3rd rib.r': { appBoneId: 'costal-cart-3-right', nameCn: '第3肋软骨（右）', nameEn: '3rd Costal Cartilage (R)', region: 'thorax', mirror: true, mirrorAppBoneId: 'costal-cart-3-left' },
  'Costal cart of 4th rib.r': { appBoneId: 'costal-cart-4-right', nameCn: '第4肋软骨（右）', nameEn: '4th Costal Cartilage (R)', region: 'thorax', mirror: true, mirrorAppBoneId: 'costal-cart-4-left' },
  'Costal cart of 5th rib.r': { appBoneId: 'costal-cart-5-right', nameCn: '第5肋软骨（右）', nameEn: '5th Costal Cartilage (R)', region: 'thorax', mirror: true, mirrorAppBoneId: 'costal-cart-5-left' },
  'Costal cart of 6th rib.r': { appBoneId: 'costal-cart-6-right', nameCn: '第6肋软骨（右）', nameEn: '6th Costal Cartilage (R)', region: 'thorax', mirror: true, mirrorAppBoneId: 'costal-cart-6-left' },
  'Costal cart of 7th rib.r': { appBoneId: 'costal-cart-7-right', nameCn: '第7肋软骨（右）', nameEn: '7th Costal Cartilage (R)', region: 'thorax', mirror: true, mirrorAppBoneId: 'costal-cart-7-left' },
  'Costal cart of 8th rib.r': { appBoneId: 'costal-cart-8-right', nameCn: '第8肋软骨（右）', nameEn: '8th Costal Cartilage (R)', region: 'thorax', mirror: true, mirrorAppBoneId: 'costal-cart-8-left' },
  'Costal cart of 9th rib.r': { appBoneId: 'costal-cart-9-right', nameCn: '第9肋软骨（右）', nameEn: '9th Costal Cartilage (R)', region: 'thorax', mirror: true, mirrorAppBoneId: 'costal-cart-9-left' },
  'Costal cart of 10th rib.r': { appBoneId: 'costal-cart-10-right', nameCn: '第10肋软骨（右）', nameEn: '10th Costal Cartilage (R)', region: 'thorax', mirror: true, mirrorAppBoneId: 'costal-cart-10-left' },
};

/**
 * Build a reverse lookup: appBoneId → BoneMappingEntry
 */
export const APP_BONE_LOOKUP: Record<string, BoneMappingEntry & { glbNodeName: string }> = {};
for (const [glbName, entry] of Object.entries(GLB_NODE_TO_BONE)) {
  APP_BONE_LOOKUP[entry.appBoneId] = { ...entry, glbNodeName: glbName };
  // Also register mirrored left-side bones
  if (entry.mirror && entry.mirrorAppBoneId) {
    const leftRegion = entry.region.replace('-right', '-left') as RegionId;
    APP_BONE_LOOKUP[entry.mirrorAppBoneId] = {
      ...entry,
      appBoneId: entry.mirrorAppBoneId,
      nameCn: entry.nameCn.replace('（右）', '（左）').replace('(R)', '(L)'),
      nameEn: entry.nameEn.replace('(R)', '(L)'),
      region: leftRegion === entry.region ? entry.region : leftRegion,
      glbNodeName: glbName + '_mirror',
      mirror: false,
    };
  }
}

/** Total bone count for display */
export const TOTAL_BONE_COUNT = Object.keys(APP_BONE_LOOKUP).length;
